### ISSUE TITLE
남은 task

### ISSUE THREAD

**Issue by darjeeling** [kboard/kboard#185]
- 계정 연동
- 설치 문서
- 설정 문서
- 문서들을 readthedoc 에 연결
- 설치는 어떻게 할것인가?
- 운영문제점은? 
- 어드민은 뭘할수 있나?
- GA 연동 
- AdSense 연동

**Comment by hyesun03** [comment]
아래 두 항목은 2.0버전(#242)으로 이동 하였습니다.
- GA 연동
- AdSense 연동
- 계정연동

**Comment by hyesun03** [comment]
남은 일감
- 설정문서
- readthedocs에 연결

계속 생각해 볼 점
- 운영문제점은?
- 어드민은 뭘할수 있나?

**Comment by hyesun03** [comment]
#249 readthedocs에 연결

**Comment by hyesun03** [comment]
#250 설정문서
