### ISSUE TITLE
django-summernote

### ISSUE THREAD

**Issue by guswnsxodlf** [kboard/kboard#55]
settings.py 내의 `STATICFILES_FINDERS`에 설정을 추가하면 summernote가 static에서 소스파일을 읽어오지 못합니다.
`STATICFILES_FINDERS` 설정은 bower를 세팅하는데에 필요합니다.

django용 summernote를 쓰지 않고 javascript로 읽어오는게 어떨까요?

**Comment by darjeeling** [comment]
`STATICFILES_FINDERS` 에 django-summernote 쪽 폴더를 추가하는건 어떨까요?

**Comment by guswnsxodlf** [comment]
STATICFILES_FINDERS에 django의 기본 항목을 추가해서 해결햇습니다.
